version: '3.8'

services:
  api-gateway-sourcing:
    build:
      context: .
      target: production
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - ALLOWED_ORIGINS=*
      - JWT_SECRET=0580eef49a4cb37116418eeca83423d85784eb7aa477ec4afe952a45f419c92868287254
      - JWT_EXPIRES=1h
      - API_KEY=sourcing_microservice_default_key_ftd@237
      - GATEWAY_SECRET=7fba8f98e172836d294b24d70b1842c94c795afa
      - GATEWAY_FORWARDER=66.33.22.177
      - GATEWAY_REAL_IP=66.33.22.177
      - PROFILE_MANAGEMENT_SERVICE_URL=http://localhost:8080
      - OFFERS_SERVICE_URL=http://localhost:8080
      - APPLICATION_SERVICE_URL=http://localhost:8080
      - MESSAGING_SERVICE_URL=http://localhost:8080
      - SMTP_SERVICE_URL=http://localhost:8080
      - REPORTING_HISTORY_SERVICE_URL=http://localhost:8080
      - MODERATION_SERVICE=http://localhost:8080
      - IMM=http://localhost:8080
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
  pm2-web:
    image: keymetrics/pm2:latest-alpine
    depends_on:
      - api-gateway-sourcing
    ports:
      - "9615:9615"
    environment:
      - PM2_WEB_STRIP_ENV_VARS=false
    restart: unless-stopped
