version: '3.8'

services:
  api-gateway-sourcing:
    build:
      context: .
      target: production
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
  pm2-web:
    image: keymetrics/pm2:latest-alpine
    depends_on:
      - api-gateway-sourcing
    ports:
      - "9615:9615"
    environment:
      - PM2_WEB_STRIP_ENV_VARS=false
    restart: unless-stopped
